Revert "Revert "Bump acorn from 6.3.0 to 6.4.1 in /oldfe""
yashin-alexander/junction2019 pull request #8
Opened 2020-04-20 11:53 UTC by dskorykh

Reverts yashin-alexander/junction2019#6

2020-04-20 11:55 UTC, dskorykh commented
@kobylyanskiy  https://github.com/yashin-alexander/junction2019/pull/7
!!!!!!!!!!!!!!!!!!

2020-04-20 11:57 UTC, kobylyanskiy commented
@dskorykh я тебе ревертну!

2020-04-20 11:59 UTC, dskorykh commented
@kobylyanskiy нас с @dependabot двое, а ты один!

2020-04-22 21:14 UTC, Seminioni commented
КААААААК ДЕЛАААА????????

2020-04-27 14:39 UTC, dskorykh commented
@Seminioni беспредел детектед

2020-04-27 15:08 UTC, kobylyanskiy requested changes
мне такое не нравится.

2020-05-05 06:38 UTC, Seminioni commented
@kobylyanskiy а кому нравится никому не нравится

2020-05-05 06:38 UTC, merged

2020-05-05 14:15 UTC, yashin-alexander commented
Approved.